// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddKeywordRequest struct {
	Keyword  string  `json:"keyword" validate:"required,min=1,max=64"`  // 关键词（必填）
	Weight   float64 `json:"weight" validate:"required,gte=-5,lte=5"`   // 权重（-5~5，必填）
	Category string  `json:"category" validate:"required,min=1,max=32"` // 分类（必填）
}

type AddKeywordResponse struct {
	BaseResponse
	Data SentimentKeyword `json:"data"` // 新增关键词详情
}

type BaseResponse struct {
	Code    int    `json:"code"`    // 状态码：0=成功，非0=失败
	Message string `json:"message"` // 提示信息
}

type GetKeywordsByCategoryRequest struct {
	Category string `form:"category" path:"category"` // 路径参数：关键词分类
}

type KeywordListResponse struct {
	BaseResponse
	Data []SentimentKeyword `json:"data"` // 关键词列表
}

type SentimentKeyword struct {
	Id        uint64  `json:"id"`        // 主键ID
	Keyword   string  `json:"keyword"`   // 情感关键词（如bullish、crash）
	Weight    float64 `json:"weight"`    // 情感权重（正数=正面，负数=负面）
	Category  string  `json:"category"`  // 分类（如crypto/stock/tech）
	Frequency int     `json:"frequency"` // 使用频率
	CreatedAt string  `json:"createdAt"` // 添加时间（ISO8601格式）
	UpdatedAt string  `json:"updatedAt"` // 更新时间（ISO8601格式）
}
