// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	keyword "tweetSentiments/internal/handler/keyword"
	"tweetSentiments/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 添加领域情感关键词（如crypto相关的bullish、bearish）
				Method:  http.MethodPost,
				Path:    "/keywords",
				Handler: keyword.AddSentimentKeywordHandler(serverCtx),
			},
			{
				// 获取指定分类的情感关键词列表
				Method:  http.MethodGet,
				Path:    "/keywords/category",
				Handler: keyword.GetKeywordsByCategoryHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
